# Generated by Django 5.0.4 on 2024-04-25 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PreEntrega', '0003_comision_estudiante'),
    ]

    operations = [
        migrations.AddField(
            model_name='comision',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='PreEntrega.curso'),
        ),
        migrations.AlterField(
            model_name='comision',
            name='nombre',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
