# Generated by Django 5.0.4 on 2024-04-25 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PreEntrega', '0004_comision_curso_alter_comision_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='curso',
        ),
        migrations.RemoveField(
            model_name='profesor',
            name='curso',
        ),
    ]
