# Generated by Django 5.0.4 on 2024-04-30 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacto',
            old_name='personas',
            new_name='persona',
        ),
        migrations.RenameField(
            model_name='direccion',
            old_name='personas',
            new_name='persona',
        ),
    ]
